import {StyleSheet} from 'react-native';
import * as Colors from './colors';
import {SCREEN} from 'src/help';

const constant = StyleSheet.create({
  textStyleBasic: {
    fontFamily: 'Inter-Regular',
    // fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 17,
    color: Colors.BLACK,
  },
});

export const styleSheet = StyleSheet.create({
  containerSafeAreaView: {flex: 1, backgroundColor: Colors.WHITE},
  helperTextStyle: {color: Colors.RED},
  linkTextStyle: {
    color: Colors.SYS_BUTTON,
    fontSize: 14,
    fontFamily: 'Inter-SemiBold',
  },
  center: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorTextStyle: {
    color: Colors.CANCLE_BUTTON,
    marginVertical: 3,
    fontSize: 12,
    fontFamily: 'Inter-Regular',
    zIndex: -1,
  },
  inputStyle: {
    paddingStart: 20,
    backgroundColor: Colors.GRAY_01,
    width: '100%',
    borderColor: Colors.GRAY_02,
    borderWidth: 1,
    borderRadius: 8,
    height: 50,
    color: Colors.BLACK,
  },
  inputPasswordStyle: {
    paddingStart: 20,
    color: Colors.BLACK,
    paddingEnd: 50,
    backgroundColor: Colors.GRAY_01,
    width: '100%',
    borderColor: Colors.GRAY_02,
    borderWidth: 1,
    borderRadius: 8,
    height: 50,
  },
  containerStyle: {
    // justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    width: '100%',
    paddingHorizontal: 20,
    backgroundColor: Colors.WHITE,
  },
  textStyleBasic: constant.textStyleBasic,
  row: {flexDirection: 'row', alignItems: 'center'},
  textStyleBold: {
    ...constant.textStyleBasic,
    fontFamily: 'Inter-SemiBold',
  },
  textStyleSub: {
    ...constant.textStyleBasic,
    color: Colors.GRAY_DARK,
    fontSize: 12,
  },
  titleTextStyle: {
    ...constant.textStyleBasic,
    fontFamily: 'Inter-SemiBold',
    marginVertical: 10,
    fontSize: 30,
    lineHeight: 36,
  },
  buttonPrimaryText: {
    ...constant.textStyleBasic,
    fontFamily: 'Inter-SemiBold',
    color: Colors.WHITE,
  },
  buttonPrimaryStyle: {
    display: 'flex',
    width: '100%',
    height: 51,
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 16,
    backgroundColor: Colors.SYS_BUTTON,
    borderRadius: 100,
    gap: 12,
    marginTop: 35,
    marginBottom: 20,
  },
  buttonDefaultStyle: {
    display: 'flex',
    width: '100%',
    height: 51,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderColor: Colors.SYS_BUTTON,
    backgroundColor: Colors.WHITE,
    borderWidth: 1,
    borderRadius: 100,
    gap: 5,
  },
  buttonDefaultText: {
    ...constant.textStyleBasic,
    fontFamily: 'Inter-SemiBold',
    color: Colors.SYS_BUTTON,
  },
  botomTab: {
    width: SCREEN.width,
    alignItems: 'center',
    zIndex: -1,
  },
  filedText: {
    ...constant.textStyleBasic,
    padding: 10,
    backgroundColor: Colors.WHITE,
    borderWidth: 1,
    borderRadius: 8,
    marginTop: 10,
    borderColor: Colors.GRAY_02,
    height: 50,
    lineHeight: 18,
    textAlignVertical: 'center',
  },
  shadown: {
    shadowColor: '#000',
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
  },
  listSpace: {
    marginBottom: 15,
  },
});
