// assets images and everything else
import {ImageSourcePropType} from 'react-native';

export const IMAGE: {[key: string]: ImageSourcePropType} = {
  DEFAULT_IMAGE: require('./images/image-default.jpg'),
  UPLOAD_IMAGE: require('./images/upload.png'),
  COMPELETED_BACKGROUND: require('./images/compeleted_background.jpg'),
  APP_BACKGROUND: require('./images/background.png'),
  FARM_DEFAULT: require('./images/farmDefault.png'),
  SEASON_DEFAULT: require('./images/seasonDefault.png'),
  SEASON_CREATE_FINISH_BACKGROUND: require('./images/finishBackgroundCreateSeason.png'),
  STAFF_BACKGROUND: require('./images/staff_background.png'),
  DIARY_BACKGROUND: require('./images/background_diary.png'),
  FARM_DEFAULT_COMPLETED: require('./images/farmDefaultCompleted.png'),
  LinearGradientWhite: require('./images/LinearGradientWhite.png'),
};

export const ICON: {[key: string]: ImageSourcePropType} = {
  diary: require('./icons/diary.png'),
  diarySelected: require('./icons/diary_selected.png'),
  home: require('./icons/home.png'),
  homeSelected: require('./icons/home_selected.png'),
  farm: require('./icons/farm.png'),
  farmSelected: require('./icons/farm_selected.png'),
  season: require('./icons/season.png'),
  seasonSelected: require('./icons/season_selected.png'),
  profile: require('./icons/profile.png'),
  profileSelected: require('./icons/profile_selected.png'),
  setting: require('./icons/settings.png'),
  filter: require('./icons/filter.png'),
  filter_selected: require('./icons/filter_selected.png'),
  arrow_r: require('./icons/arrow_r.png'),
  checkbox: require('./icons/checkbox.png'),
  checkbox_active: require('./icons/checkbox_active.png'),
  create: require('./icons/create.png'),
  calendar: require('./icons/calendar.png'),
  crops: require('./icons/crops.png'),
  shovel: require('./icons/shovel.png'),
  supplies: require('./icons/supplies.png'),
  clock: require('./icons/clock.png'),
  addFile: require('./icons/addFile.png'),
  pin: require('./icons/map-pin.png'),
  pinBig: require('./icons/map-pin-big.png'),

  defaultImgBackground: require('./icons/defaultImgBackground.png'),
  uploadIcon: require('./icons/uploadIcon.png'),
  trash: require('./icons/trash.png'),
  pencil: require('./icons/pencil.png'),
  camera: require('./icons/camera.png'),
  boxEmpty: require('./icons/box_empty.png'),
  users: require('./icons/users.png'),
  notification: require('./icons/notification.png'),
  QR_code_Square: require('./icons/QR_code_Square.png'),
  QRcode: require('./icons/QRcode.png'),
  sun: require('./icons/sun.png'),
  rain: require('./icons/rain.png'),
  temperature: require('./icons/temperature.png'),
  video: require('./icons/video.png'),
  news: require('./icons/news.png'),
  user: require('./icons/user.png'),
  shield: require('./icons/shield.png'),
  file: require('./icons/file.png'),
  logOut: require('./icons/log-out.png'),
  add_staff: require('./icons/add_staff.png'),
  staff_avatar: require('./icons/staff_avatar.png'),
  line: require('./icons/line.png'),
  circle: require('./icons/circle.png'),
  checkCircle: require('./icons/check-circle.png'),
  location: require('./icons/location.png'),
  arrow_d: require('./icons/arrow_d.png'),
  exclamation: require('./icons/exclamation.png'),
  cropsShovel: require('./icons/crops-shovel.png'),
  market: require('./icons/market.png'),
  papers: require('./icons/papers.png'),
  farmLocationIcon: require('./icons/farm-location-icon.png'),
  map: require('./icons/map-icon-01.png'),
  phone: require('./icons/phone-icon-01.png'),
  face_id: require('./icons/face-id.png'),
  fingerprint: require('./icons/fingerprint.png'),
  share: require('./icons/share.png'),
  borderQrCode: require('./icons/borderQrCode.png'),
  view: require('./icons/view.png'),
  hide: require('./icons/hide.png'),
  correct: require('./icons/correct.png'),
  play: require('./icons/play.png'),
  bell: require('./icons/bell.png'),
  bellSelected: require('./icons/bell_selected.png'),
  userMyLocation: require('./icons/userMyLocation.png'),
  area: require('./icons/area.png'),
  GCN: require('./icons/GCN.png'),
  add_ICON: require('./icons/addIcon.png'),
  remove_ICON: require('./icons/removeIcon.png'),
  remove_ICON_DISABLED: require('./icons/RemoveIconDisabeld.png'),
  app_icon: require('./icons/ic_launcher_playstore.png'),
};

export const GIF: {[key: string]: ImageSourcePropType} = {
  upload: require('./gif/upload.gif'),
};
